language: java

jdk:
  - oraclejdk7

before_install:
  - sudo apt-get update -qq
  - sudo apt-get install automake bison flex g++ git libboost-all-dev libevent-dev libssl-dev libtool make pkg-config
  - wget http://ftp.debian.org/debian/pool/main/a/automake-1.15/automake_1.15-3_all.deb
  - sudo dpkg -i automake_1.15-3_all.deb
  - wget http://sourceforge.net/projects/boost/files/boost/1.60.0/boost_1_60_0.tar.gz                                                                      
  - tar xvf boost_1_60_0.tar.gz
  - cd boost_1_60_0
  - ./bootstrap.sh
  - sudo ./b2 install
  - wget http://www.us.apache.org/dist/thrift/0.9.3/thrift-0.9.3.tar.gz
  - tar xfz thrift-0.9.3.tar.gz
  - cd thrift-0.9.3 && ./configure && sudo make install

install: gradle -q assemble

script: gradle clean check distZip --stacktrace